BEGIN

EXECUTE IMMEDIATE 'TRUNCATE TABLE part';
EXECUTE IMMEDIATE 'TRUNCATE TABLE supplier';
EXECUTE IMMEDIATE 'TRUNCATE TABLE partsupp';
EXECUTE IMMEDIATE 'TRUNCATE TABLE customer';
EXECUTE IMMEDIATE 'TRUNCATE TABLE orders';
EXECUTE IMMEDIATE 'TRUNCATE TABLE lineitem';
EXECUTE IMMEDIATE 'TRUNCATE TABLE nation';
EXECUTE IMMEDIATE 'TRUNCATE TABLE region';

EXECUTE IMMEDIATE 'INSERT /*+ APPEND */ INTO  part     SELECT * FROM c##tpch.ext_part';
EXECUTE IMMEDIATE 'INSERT /*+ APPEND */ INTO  supplier SELECT * FROM c##tpch.ext_supplier';
EXECUTE IMMEDIATE 'INSERT /*+ APPEND */ INTO  partsupp SELECT * FROM c##tpch.ext_partsupp';
EXECUTE IMMEDIATE 'INSERT /*+ APPEND */ INTO  customer SELECT * FROM c##tpch.ext_customer';
EXECUTE IMMEDIATE 'INSERT /*+ APPEND */ INTO  orders   SELECT * FROM c##tpch.ext_orders';
EXECUTE IMMEDIATE 'INSERT /*+ APPEND */ INTO  lineitem SELECT * FROM c##tpch.ext_lineitem';
EXECUTE IMMEDIATE 'INSERT /*+ APPEND */ INTO  nation   SELECT * FROM c##tpch.ext_nation';
EXECUTE IMMEDIATE 'INSERT /*+ APPEND */ INTO  region   SELECT * FROM c##tpch.ext_region';

EXECUTE IMMEDIATE 'COMMIT';

END;

