BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE REGION ADD PRIMARY KEY (R_REGIONKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE NATION ADD PRIMARY KEY (N_NATIONKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMER ADD PRIMARY KEY (C_CUSTKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE SUPPLIER ADD PRIMARY KEY (S_SUPPKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE PART ADD PRIMARY KEY (P_PARTKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE PARTSUPP ADD PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE ORDERS ADD PRIMARY KEY (O_ORDERKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE LINEITEM ADD PRIMARY KEY (L_ORDERKEY, L_LINENUMBER)';
    EXECUTE IMMEDIATE 'ALTER TABLE NATION ADD FOREIGN KEY (N_REGIONKEY) REFERENCES
        REGION(R_REGIONKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE SUPPLIER ADD FOREIGN KEY (S_NATIONKEY) REFERENCES
        NATION(N_NATIONKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE CUSTOMER ADD FOREIGN KEY (C_NATIONKEY) REFERENCES
        NATION(N_NATIONKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE PARTSUPP ADD FOREIGN KEY (PS_SUPPKEY) REFERENCES
        SUPPLIER(S_SUPPKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE PARTSUPP ADD FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE ORDERS ADD FOREIGN KEY (O_CUSTKEY) REFERENCES
        CUSTOMER(C_CUSTKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE LINEITEM ADD FOREIGN KEY (L_ORDERKEY) REFERENCES
        ORDERS(O_ORDERKEY)';
    EXECUTE IMMEDIATE 'ALTER TABLE LINEITEM ADD FOREIGN KEY (L_PARTKEY,L_SUPPKEY) REFERENCES
        PARTSUPP(PS_PARTKEY,PS_SUPPKEY)';
END;